# Transformation
간단한 데이터 변형과 결합을 연습한다.
데이터를 정리하고 보고서용 형태로 바꾸는 기본 흐름에 해당한다.

## apply, map, replace
값을 하나씩 가공하거나, 코드 값을 사람이 읽기 쉬운 값으로 바꾸거나 특정 값을 다른 값으로 치환할 때 사용하는 기능

In [3]:
import pandas as pd 
import numpy as np 

# 예제 데이터 프레임
df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수'],
    '점수': [85, 92, 78],
    '성별': ['M', 'F', 'M']
})
df

    이름  점수 성별
0  김철수  85  M
1  이영희  92  F
2  박민수  78  M

In [ ]:
# apply : 각 점수에 5점을 더해 조정 점수 컬럼 만들기
# 한 컬럼의 값을 하나씩 가공할 때 사용
df['조정점수'] = df['점수'].apply(lambda x: x + 5)
df

    이름  점수 성별  조정점수
0  김철수  85  M    90
1  이영희  92  F    97
2  박민수  78  M    83

In [ ]:
# apply : 함수로 등급 만들기
def grade(x):
    if x >= 90:
        return 'A'
    elif x >= 80:
        return 'B'
    else:
        return 'C'